spring:
  rabbitmq:
    host: 124.221.123.200
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    root: info