version: '3'
services:
  #MOSS Mysql数据库初使化
  moss-db-init:
    image: mysql:5.7
    command: /init-db.sh
    networks:
      - sc-net
    volumes:
      - ./moss/mysql:/sql
      - ./init-db.sh:/init-db.sh
    environment:
      MYSQL_ROOT_PASSWORD: root123
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          cpus: '0.1'
          memory: 64M

  #Moss管理中心
  moss:
    image: w304807481/moss-web:latest
    container_name: moss
    restart: always
    networks:
      - sc-net
    ports:
      - 8086:8086
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - moss-db-init
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          memory: 64M