version: '3'
services:
  #授权服务
  authorization-server:
    image: cike/authorization-server:latest
    container_name: sc-authorization-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8000:8000
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - authentication-server
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          memory: 64M

  #认证服务
  authentication-server:
    image: cike/authentication-server:latest
    container_name: sc-authentication-server
    restart: always
    networks:
      - sc-net
    ports:
      - 8001:8001
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    depends_on:
      - organization
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          memory: 64M

  #组织服务
  organization:
    image: cike/organization:latest
    container_name: sc-organization
    restart: always
    networks:
      - sc-net
    ports:
      - 8010:8010
    env_file: .env
    environment:
      TZ: Asia/Shanghai
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.10'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          memory: 64M