version: '3'
services:

  konga:
    image: pantsel/konga
    container_name: sc-konga
    depends_on:
      - kong
    networks:
      - sc-net
    env_file: .env
    ports:
      - 1337:1337/tcp
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          cpus: '0.1'
          memory: 64M

  kong:
    image: kong:latest
    container_name: sc-kong
    env_file: .env
    volumes:
      - ../data/kong:/usr/local/kong
    networks:
      - sc-net
    ports:
      - 18000:8000/tcp
      - 18443:8443/tcp
      - 18001:8001/tcp
      - 8444:8444/tcp
    depends_on:
      - postgres
    deploy:
      resources:
        # 设置容器的资源限制
        limits:
          cpus: '0.20'
          memory: 128M
        #设置为容器预留的系统资源(随时可用)
        reservations:
          memory: 64M
    environment:
      - JAVA_OPTS=-Xmx100m -Xms50m -Xss1m
